/* v0.8 global market list — real cities, grouped by country.
 * Used to build a fresh local query for every discovery run so research is never
 * stuck on the same handful of cities. Countries not listed here still rotate
 * through the broad mode (every country and territory) using a real city in it.
 */
export const MARKET_CITIES = {
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Austin", "Seattle", "Denver", "Atlanta", "Miami", "Boston", "Portland", "Nashville", "Minneapolis", "San Diego"],
  GB: ["London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Bristol", "Sheffield", "Newcastle", "Nottingham", "Leicester", "Glasgow", "Edinburgh", "Cardiff", "Belfast", "Brighton"],
  CA: ["Toronto", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Halifax", "Victoria", "Saskatoon", "London"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Hobart", "Darwin", "Newcastle", "Geelong", "Gold Coast", "Cairns"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Napier"],
  IE: ["Dublin", "Cork", "Galway", "Limerick", "Waterford", "Kilkenny"],
  DE: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Leipzig", "Dresden", "Hanover", "Nuremberg", "Bremen"],
  FR: ["Paris", "Lyon", "Marseille", "Toulouse", "Nantes", "Bordeaux", "Lille", "Strasbourg", "Nice", "Rennes", "Montpellier"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Haarlem"],
  BE: ["Brussels", "Antwerp", "Ghent", "Bruges", "Leuven", "Liège"],
  ES: ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Málaga", "Zaragoza", "Granada", "Murcia"],
  PT: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro", "Aveiro"],
  IT: ["Milan", "Rome", "Turin", "Bologna", "Florence", "Naples", "Genoa", "Verona", "Palermo"],
  CH: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne"],
  AT: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  SE: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Linköping", "Örebro"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen"],
  DK: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  FI: ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu"],
  PL: ["Warsaw", "Kraków", "Wrocław", "Poznań", "Gdańsk", "Łódź", "Katowice"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň", "Olomouc"],
  HU: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  RO: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Brașov", "Constanța"],
  GR: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  TR: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya"],
  RU: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Samara"],
  UA: ["Kyiv", "Lviv", "Odesa", "Kharkiv", "Dnipro"],
  AE: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras Al Khaimah"],
  SA: ["Riyadh", "Jeddah", "Dammam", "Mecca", "Medina", "Khobar"],
  QA: ["Doha", "Al Rayyan", "Al Wakrah", "Lusail"],
  KW: ["Kuwait City", "Hawalli", "Salmiya", "Al Ahmadi"],
  BH: ["Manama", "Riffa", "Muharraq", "Isa Town"],
  OM: ["Muscat", "Salalah", "Sohar", "Nizwa"],
  IL: ["Tel Aviv", "Jerusalem", "Haifa", "Beersheba", "Netanya"],
  EG: ["Cairo", "Alexandria", "Giza", "Port Said", "Luxor"],
  MA: ["Casablanca", "Rabat", "Marrakesh", "Fès", "Tangier", "Agadir"],
  DZ: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  TN: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London"],
  NG: ["Lagos", "Abuja", "Port Harcourt", "Ibadan", "Kano", "Benin City", "Enugu"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  GH: ["Accra", "Kumasi", "Tamale", "Takoradi", "Tema"],
  TZ: ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza", "Zanzibar City"],
  UG: ["Kampala", "Entebbe", "Gulu", "Mbarara", "Jinja"],
  ET: ["Addis Ababa", "Dire Dawa", "Mekelle", "Bahir Dar", "Hawassa"],
  CM: ["Douala", "Yaoundé", "Bafoussam", "Garoua", "Bamenda"],
  CI: ["Abidjan", "Yamoussoukro", "Bouaké", "San-Pédro", "Korhogo"],
  SN: ["Dakar", "Touba", "Thiès", "Saint-Louis", "Ziguinchor"],
  MW: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"],
  ZM: ["Lusaka", "Kitwe", "Ndola", "Livingstone"],
  ZW: ["Harare", "Bulawayo", "Mutare", "Gweru"],
  BW: ["Gaborone", "Francistown", "Maun", "Molepolole"],
  NA: ["Windhoek", "Walvis Bay", "Swakopmund", "Oshakati"],
  MU: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe"],
  IN: ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat", "Kochi", "Indore", "Lucknow", "Chandigarh", "Coimbatore"],
  BD: ["Dhaka", "Chattogram", "Sylhet", "Khulna", "Rajshahi", "Gazipur", "Bogura", "Cumilla", "Narayanganj", "Cox's Bazar"],
  PK: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar", "Quetta"],
  LK: ["Colombo", "Kandy", "Galle", "Negombo", "Jaffna"],
  NP: ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar"],
  ID: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Denpasar", "Yogyakarta"],
  MY: ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Kota Kinabalu", "Kuching", "Malacca City"],
  SG: ["Singapore", "Jurong", "Woodlands", "Tampines"],
  TH: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Khon Kaen", "Hat Yai"],
  VN: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Hue"],
  PH: ["Manila", "Quezon City", "Cebu City", "Davao City", "Iloilo City", "Makati", "Bacolod"],
  KH: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"],
  MM: ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine"],
  CN: ["Shanghai", "Beijing", "Shenzhen", "Guangzhou", "Hangzhou", "Chengdu", "Wuhan", "Xi'an", "Suzhou"],
  HK: ["Hong Kong", "Kowloon", "Tsuen Wan", "Sha Tin"],
  TW: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  JP: ["Tokyo", "Osaka", "Nagoya", "Fukuoka", "Sapporo", "Kobe", "Kyoto", "Yokohama"],
  MN: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"],
  KZ: ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe"],
  UZ: ["Tashkent", "Samarkand", "Bukhara", "Namangan", "Andijan"],
  GE: ["Tbilisi", "Batumi", "Kutaisi", "Rustavi"],
  AM: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat"],
  AZ: ["Baku", "Ganja", "Sumqayit", "Lankaran"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Belo Horizonte", "Curitiba", "Recife", "Porto Alegre", "Fortaleza", "Manaus", "Florianópolis"],
  MX: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Cancún", "Mérida", "Querétaro"],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Mar del Plata"],
  CL: ["Santiago", "Valparaíso", "Concepción", "Antofagasta", "Viña del Mar"],
  CO: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Bucaramanga"],
  PE: ["Lima", "Arequipa", "Trujillo", "Cusco", "Piura"],
  EC: ["Quito", "Guayaquil", "Cuenca", "Ambato", "Manta"],
  UY: ["Montevideo", "Punta del Este", "Salto", "Paysandú"],
  PY: ["Asunción", "Ciudad del Este", "Encarnación", "San Lorenzo"],
  BO: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre", "El Alto"],
  CR: ["San José", "Alajuela", "Cartago", "Heredia", "Liberia"],
  PA: ["Panama City", "Colón", "David", "La Chorrera"],
  GT: ["Guatemala City", "Quetzaltenango", "Escuintla", "Antigua Guatemala"],
  DO: ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "Puerto Plata"],
  JM: ["Kingston", "Montego Bay", "Spanish Town", "Ocho Ríos"],
  TT: ["Port of Spain", "San Fernando", "Chaguanas", "Arima"],
  BB: ["Bridgetown", "Speightstown", "Oistins", "Holetown"],
  BS: ["Nassau", "Freeport", "Marsh Harbour"],
  FJ: ["Suva", "Nadi", "Lautoka", "Labasa"],
  PG: ["Port Moresby", "Lae", "Mount Hagen", "Madang"],
  WS: ["Apia", "Vaitele", "Faleula"],
  TO: ["Nuku'alofa", "Neiafu", "Haveluloto"],
  VU: ["Port Vila", "Luganville", "Isangel"],
  SB: ["Honiara", "Auki", "Gizo"],
  NC: ["Nouméa", "Mont-Dore", "Dumbéa"],
  PF: ["Papeete", "Faaa", "Punaauia"],
  GU: ["Hagåtña", "Tamuning", "Dededo"],
  IS: ["Reykjavík", "Kópavogur", "Hafnarfjörður", "Akureyri"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  RS: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  BA: ["Sarajevo", "Banja Luka", "Tuzla", "Mostar", "Zenica"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Ohrid"],
  AL: ["Tirana", "Durrës", "Vlorë", "Shkodër", "Elbasan"],
  BG: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  MD: ["Chișinău", "Bălți", "Tiraspol", "Cahul"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  LV: ["Riga", "Daugavpils", "Liepāja", "Jelgava"],
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj"],
  SK: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"],
  CY: ["Nicosia", "Limassol", "Larnaca", "Paphos"],
  MT: ["Valletta", "Birkirkara", "Sliema", "Mosta"],
  LU: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange"],
  IM: ["Douglas", "Ramsey", "Peel", "Castletown"],
  JE: ["Saint Helier", "Saint Brelade", "Saint Clement"],
  GG: ["Saint Peter Port", "Vale", "Saint Sampson"],
};
/* Kept as a plain number for older callers, plus a shaped summary the UI shows. */
export const marketCityCount = Object.values(MARKET_CITIES).reduce(
  (n, c) => n + c.length,
  0,
);
export const marketSummary = {
  countries: Object.keys(MARKET_CITIES).length,
  cities: marketCityCount,
};
export function citiesFor(code) {
  const list = MARKET_CITIES[code];
  return Array.isArray(list) && list.length ? list : null;
}
export function cityFor(code, seed = 0) {
  const list = citiesFor(code);
  if (!list) return null;
  const i = Math.abs(Math.floor(Number(seed) || 0)) % list.length;
  return list[i];
}
